"""
kegg_names.py – Complete KEGG pathway name lookup (generated from KEGG REST API)

Source: https://rest.kegg.jp/list/pathway

Both 'ko' and 'map' keys are provided:
  - map entries = KEGG reference pathway maps (biological pathway diagrams)
  - ko  entries = KO-based pathways (which genes have KO assignments in that pathway)

They are biologically related (same number) but represent different KEGG concepts.
Both are included so any code from annotation data resolves to a readable name.

Usage:
    from kegg_names import pathway_label
    pathway_label('ko04010')   # 'MAPK signaling pathway'
    pathway_label('map04010')  # 'MAPK signaling pathway'
"""

_MAP = {
    # === Metabolism – Overview ===
    'map01100': 'Metabolic pathways',
    'map01110': 'Biosynthesis of secondary metabolites',
    'map01120': 'Microbial metabolism in diverse environments',
    'map01200': 'Carbon metabolism',
    'map01210': '2-Oxocarboxylic acid metabolism',
    'map01212': 'Fatty acid metabolism',
    'map01230': 'Biosynthesis of amino acids',
    'map01232': 'Nucleotide metabolism',
    'map01250': 'Biosynthesis of nucleotide sugars',
    'map01240': 'Biosynthesis of cofactors',
    'map01220': 'Degradation of aromatic compounds',
    'map01310': 'Nitrogen cycle',
    'map01320': 'Sulfur cycle',
    # === Carbohydrate metabolism ===
    'map00010': 'Glycolysis / Gluconeogenesis',
    'map00020': 'Citrate cycle (TCA cycle)',
    'map00030': 'Pentose phosphate pathway',
    'map00040': 'Pentose and glucuronate interconversions',
    'map00051': 'Fructose and mannose metabolism',
    'map00052': 'Galactose metabolism',
    'map00053': 'Ascorbate and aldarate metabolism',
    'map00500': 'Starch and sucrose metabolism',
    'map00620': 'Pyruvate metabolism',
    'map00630': 'Glyoxylate and dicarboxylate metabolism',
    'map00640': 'Propanoate metabolism',
    'map00650': 'Butanoate metabolism',
    'map00660': 'C5-Branched dibasic acid metabolism',
    'map00562': 'Inositol phosphate metabolism',
    'map00566': 'Sulfoquinovose metabolism',
    # === Energy metabolism ===
    'map00190': 'Oxidative phosphorylation',
    'map00195': 'Photosynthesis',
    'map00196': 'Photosynthesis - antenna proteins',
    'map00710': 'Carbon fixation by Calvin cycle',
    'map00720': 'Other carbon fixation pathways',
    'map00680': 'Methane metabolism',
    'map00910': 'Nitrogen metabolism',
    'map00920': 'Sulfur metabolism',
    # === Lipid metabolism ===
    'map00061': 'Fatty acid biosynthesis',
    'map00062': 'Fatty acid elongation',
    'map00071': 'Fatty acid degradation',
    'map00073': 'Cutin, suberine and wax biosynthesis',
    'map00074': 'Mycolic acid biosynthesis',
    'map00100': 'Steroid biosynthesis',
    'map00120': 'Primary bile acid biosynthesis',
    'map00121': 'Secondary bile acid biosynthesis',
    'map00140': 'Steroid hormone biosynthesis',
    'map00561': 'Glycerolipid metabolism',
    'map00564': 'Glycerophospholipid metabolism',
    'map00565': 'Ether lipid metabolism',
    'map00600': 'Sphingolipid metabolism',
    'map00590': 'Arachidonic acid metabolism',
    'map00591': 'Linoleic acid metabolism',
    'map00592': 'alpha-Linolenic acid metabolism',
    'map01040': 'Biosynthesis of unsaturated fatty acids',
    # === Nucleotide metabolism ===
    'map00230': 'Purine metabolism',
    'map00240': 'Pyrimidine metabolism',
    # === Amino acid metabolism ===
    'map00250': 'Alanine, aspartate and glutamate metabolism',
    'map00260': 'Glycine, serine and threonine metabolism',
    'map00270': 'Cysteine and methionine metabolism',
    'map00280': 'Valine, leucine and isoleucine degradation',
    'map00290': 'Valine, leucine and isoleucine biosynthesis',
    'map00300': 'Lysine biosynthesis',
    'map00310': 'Lysine degradation',
    'map00220': 'Arginine biosynthesis',
    'map00330': 'Arginine and proline metabolism',
    'map00340': 'Histidine metabolism',
    'map00350': 'Tyrosine metabolism',
    'map00360': 'Phenylalanine metabolism',
    'map00380': 'Tryptophan metabolism',
    'map00400': 'Phenylalanine, tyrosine and tryptophan biosynthesis',
    'map00410': 'beta-Alanine metabolism',
    'map00430': 'Taurine and hypotaurine metabolism',
    'map00440': 'Phosphonate and phosphinate metabolism',
    'map00450': 'Selenocompound metabolism',
    'map00460': 'Cyanoamino acid metabolism',
    'map00470': 'D-Amino acid metabolism',
    'map00480': 'Glutathione metabolism',
    # === Glycan biosynthesis ===
    'map00520': 'Amino sugar and nucleotide sugar metabolism',
    'map00510': 'N-Glycan biosynthesis',
    'map00513': 'Various types of N-glycan biosynthesis',
    'map00512': 'Mucin type O-glycan biosynthesis',
    'map00515': 'Mannose type O-glycan biosynthesis',
    'map00514': 'Other types of O-glycan biosynthesis',
    'map00532': 'Glycosaminoglycan biosynthesis - chondroitin/dermatan sulfate',
    'map00534': 'Glycosaminoglycan biosynthesis - heparan sulfate/heparin',
    'map00533': 'Glycosaminoglycan biosynthesis - keratan sulfate',
    'map00531': 'Glycosaminoglycan degradation',
    'map00563': 'GPI-anchor biosynthesis',
    'map00601': 'Glycosphingolipid biosynthesis - lacto/neolacto series',
    'map00603': 'Glycosphingolipid biosynthesis - globo/isoglobo series',
    'map00604': 'Glycosphingolipid biosynthesis - ganglio series',
    'map00511': 'Other glycan degradation',
    'map00540': 'Lipopolysaccharide biosynthesis',
    'map00550': 'Peptidoglycan biosynthesis',
    # === Cofactors and vitamins ===
    'map00730': 'Thiamine metabolism',
    'map00740': 'Riboflavin metabolism',
    'map00750': 'Vitamin B6 metabolism',
    'map00760': 'Nicotinate and nicotinamide metabolism',
    'map00770': 'Pantothenate and CoA biosynthesis',
    'map00780': 'Biotin metabolism',
    'map00785': 'Lipoic acid metabolism',
    'map00790': 'Folate biosynthesis',
    'map00670': 'One carbon pool by folate',
    'map00830': 'Retinol metabolism',
    'map00860': 'Porphyrin metabolism',
    'map00130': 'Ubiquinone and other terpenoid-quinone biosynthesis',
    # === Terpenoids and polyketides ===
    'map00900': 'Terpenoid backbone biosynthesis',
    'map00902': 'Monoterpenoid biosynthesis',
    'map00909': 'Sesquiterpenoid and triterpenoid biosynthesis',
    'map00904': 'Diterpenoid biosynthesis',
    'map00906': 'Carotenoid biosynthesis',
    'map00905': 'Brassinosteroid biosynthesis',
    'map00981': 'Insect hormone biosynthesis',
    'map00908': 'Zeatin biosynthesis',
    # === Secondary metabolites ===
    'map00940': 'Phenylpropanoid biosynthesis',
    'map00945': 'Stilbenoid, diarylheptanoid and gingerol biosynthesis',
    'map00941': 'Flavonoid biosynthesis',
    'map00944': 'Flavone and flavonol biosynthesis',
    'map00942': 'Anthocyanin biosynthesis',
    'map00943': 'Isoflavonoid biosynthesis',
    'map00901': 'Indole alkaloid biosynthesis',
    'map00950': 'Isoquinoline alkaloid biosynthesis',
    'map00960': 'Tropane, piperidine and pyridine alkaloid biosynthesis',
    'map00232': 'Caffeine metabolism',
    'map00965': 'Betalain biosynthesis',
    'map00966': 'Glucosinolate biosynthesis',
    'map00980': 'Metabolism of xenobiotics by cytochrome P450',
    'map00982': 'Drug metabolism - cytochrome P450',
    'map00983': 'Drug metabolism - other enzymes',
    # === Genetic information processing – Transcription ===
    'map03020': 'RNA polymerase',
    'map03022': 'Basal transcription factors',
    'map03040': 'Spliceosome',
    # === Genetic information processing – Translation ===
    'map03010': 'Ribosome',
    'map00970': 'Aminoacyl-tRNA biosynthesis',
    'map03013': 'Nucleocytoplasmic transport',
    'map03015': 'mRNA surveillance pathway',
    'map03008': 'Ribosome biogenesis in eukaryotes',
    # === Genetic information processing – Folding/sorting/degradation ===
    'map03060': 'Protein export',
    'map04141': 'Protein processing in endoplasmic reticulum',
    'map04130': 'SNARE interactions in vesicular transport',
    'map04120': 'Ubiquitin mediated proteolysis',
    'map04122': 'Sulfur relay system',
    'map03050': 'Proteasome',
    'map03018': 'RNA degradation',
    # === Genetic information processing – Replication/repair ===
    'map03030': 'DNA replication',
    'map03410': 'Base excision repair',
    'map03420': 'Nucleotide excision repair',
    'map03430': 'Mismatch repair',
    'map03440': 'Homologous recombination',
    'map03450': 'Non-homologous end-joining',
    'map03460': 'Fanconi anemia pathway',
    # === Transport and catabolism ===
    'map04144': 'Endocytosis',
    'map04145': 'Phagosome',
    'map04142': 'Lysosome',
    'map04146': 'Peroxisome',
    'map04140': 'Autophagy - animal',
    'map04138': 'Autophagy - yeast',
    'map04136': 'Autophagy - other',
    'map04137': 'Mitophagy - animal',
    'map04139': 'Mitophagy - yeast',
    'map04148': 'Efferocytosis',
    # === Cell growth and death ===
    'map04110': 'Cell cycle',
    'map04111': 'Cell cycle - yeast',
    'map04114': 'Oocyte meiosis',
    'map04210': 'Apoptosis',
    'map04214': 'Apoptosis - fly',
    'map04215': 'Apoptosis - multiple species',
    'map04216': 'Ferroptosis',
    'map04217': 'Necroptosis',
    'map04115': 'p53 signaling pathway',
    'map04218': 'Cellular senescence',
    # === Cell communication – Signal transduction ===
    'map04010': 'MAPK signaling pathway',
    'map04013': 'MAPK signaling pathway - fly',
    'map04014': 'Ras signaling pathway',
    'map04015': 'Rap1 signaling pathway',
    'map04310': 'Wnt signaling pathway',
    'map04330': 'Notch signaling pathway',
    'map04340': 'Hedgehog signaling pathway',
    'map04341': 'Hedgehog signaling pathway - fly',
    'map04350': 'TGF-beta signaling pathway',
    'map04390': 'Hippo signaling pathway',
    'map04391': 'Hippo signaling pathway - fly',
    'map04392': 'Hippo signaling pathway - multiple species',
    'map04370': 'VEGF signaling pathway',
    'map04371': 'Apelin signaling pathway',
    'map04630': 'JAK-STAT signaling pathway',
    'map04064': 'NF-kappa B signaling pathway',
    'map04668': 'TNF signaling pathway',
    'map04066': 'HIF-1 signaling pathway',
    'map04068': 'FoxO signaling pathway',
    'map04020': 'Calcium signaling pathway',
    'map04070': 'Phosphatidylinositol signaling system',
    'map04072': 'Phospholipase D signaling pathway',
    'map04071': 'Sphingolipid signaling pathway',
    'map04024': 'cAMP signaling pathway',
    'map04022': 'cGMP-PKG signaling pathway',
    'map04151': 'PI3K-Akt signaling pathway',
    'map04152': 'AMPK signaling pathway',
    'map04150': 'mTOR signaling pathway',
    'map04012': 'ErbB signaling pathway',
    # === Cell communication – Signaling molecules ===
    'map04080': 'Neuroactive ligand-receptor interaction',
    'map04060': 'Cytokine-cytokine receptor interaction',
    'map04061': 'Viral protein interaction with cytokine receptor',
    # === Cellular community – ECM/adhesion ===
    'map04510': 'Focal adhesion',
    'map04512': 'ECM-receptor interaction',
    'map04514': 'Cell adhesion molecules (CAMs)',
    'map04520': 'Adherens junction',
    'map04530': 'Tight junction',
    'map04540': 'Gap junction',
    'map04550': 'Signaling pathways regulating pluripotency of stem cells',
    'map04810': 'Regulation of actin cytoskeleton',
    'map04814': 'Motor proteins',
    'map04820': 'Cytoskeleton in muscle cells',
    # === Immune system ===
    'map04640': 'Hematopoietic cell lineage',
    'map04610': 'Complement and coagulation cascades',
    'map04611': 'Platelet activation',
    'map04613': 'Neutrophil extracellular trap formation',
    'map04620': 'Toll-like receptor signaling pathway',
    'map04621': 'NOD-like receptor signaling pathway',
    'map04622': 'RIG-I-like receptor signaling pathway',
    'map04623': 'Cytosolic DNA-sensing pathway',
    'map04624': 'Toll and Imd signaling pathway',
    'map04625': 'C-type lectin receptor signaling pathway',
    'map04650': 'Natural killer cell mediated cytotoxicity',
    'map04612': 'Antigen processing and presentation',
    'map04660': 'T cell receptor signaling pathway',
    'map04658': 'Th1 and Th2 cell differentiation',
    'map04659': 'Th17 cell differentiation',
    'map04657': 'IL-17 signaling pathway',
    'map04662': 'B cell receptor signaling pathway',
    'map04664': 'Fc epsilon RI signaling pathway',
    'map04666': 'Fc gamma R-mediated phagocytosis',
    'map04670': 'Leukocyte transendothelial migration',
    'map04672': 'Intestinal immune network for IgA production',
    'map04062': 'Chemokine signaling pathway',
    # === Endocrine system ===
    'map04911': 'Insulin secretion',
    'map04910': 'Insulin signaling pathway',
    'map04922': 'Glucagon signaling pathway',
    'map04923': 'Regulation of lipolysis in adipocytes',
    'map04920': 'Adipocytokine signaling pathway',
    'map03320': 'PPAR signaling pathway',
    'map04912': 'GnRH signaling pathway',
    'map04913': 'Ovarian steroidogenesis',
    'map04915': 'Estrogen signaling pathway',
    'map04914': 'Progesterone-mediated oocyte maturation',
    'map04917': 'Prolactin signaling pathway',
    'map04921': 'Oxytocin signaling pathway',
    'map04926': 'Relaxin signaling pathway',
    'map04918': 'Thyroid hormone synthesis',
    'map04919': 'Thyroid hormone signaling pathway',
    'map04916': 'Melanogenesis',
    'map04614': 'Renin-angiotensin system',
    # === Circulatory/digestive system ===
    'map04260': 'Cardiac muscle contraction',
    'map04261': 'Adrenergic signaling in cardiomyocytes',
    'map04270': 'Vascular smooth muscle contraction',
    'map04970': 'Salivary secretion',
    'map04971': 'Gastric acid secretion',
    'map04972': 'Pancreatic secretion',
    'map04976': 'Bile secretion',
    'map04973': 'Carbohydrate digestion and absorption',
    'map04974': 'Protein digestion and absorption',
    'map04975': 'Fat digestion and absorption',
    'map04979': 'Cholesterol metabolism',
    'map04977': 'Vitamin digestion and absorption',
    'map04978': 'Mineral absorption',
    'map04962': 'Vasopressin-regulated water reabsorption',
    'map04960': 'Aldosterone-regulated sodium reabsorption',
    'map04961': 'Endocrine-regulated calcium reabsorption',
    'map04964': 'Proximal tubule bicarbonate reclamation',
    # === Nervous system ===
    'map04724': 'Glutamatergic synapse',
    'map04727': 'GABAergic synapse',
    'map04725': 'Cholinergic synapse',
    'map04728': 'Dopaminergic synapse',
    'map04726': 'Serotonergic synapse',
    'map04720': 'Long-term potentiation',
    'map04730': 'Long-term depression',
    'map04723': 'Retrograde endocannabinoid signaling',
    'map04721': 'Synaptic vesicle cycle',
    'map04722': 'Neurotrophin signaling pathway',
    'map04744': 'Phototransduction',
    'map04740': 'Olfactory transduction',
    'map04742': 'Taste transduction',
    # === Development ===
    'map04320': 'Dorso-ventral axis formation',
    'map04360': 'Axon guidance',
    'map04361': 'Axon regeneration',
    'map04380': 'Osteoclast differentiation',
    # === Aging ===
    'map04211': 'Longevity regulating pathway',
    'map04213': 'Longevity regulating pathway - multiple species',
    # === Environmental adaptation ===
    'map04710': 'Circadian rhythm',
    'map04713': 'Circadian entrainment',
    'map04711': 'Circadian rhythm - fly',
    'map04714': 'Thermogenesis',
    # === Cancer ===
    'map05200': 'Pathways in cancer',
    'map05202': 'Transcriptional misregulation in cancer',
    'map05206': 'MicroRNAs in cancer',
    'map05205': 'Proteoglycans in cancer',
    'map05203': 'Viral carcinogenesis',
    'map05230': 'Central carbon metabolism in cancer',
    'map05231': 'Choline metabolism in cancer',
    'map05210': 'Colorectal cancer',
    'map05212': 'Pancreatic cancer',
    'map05225': 'Hepatocellular carcinoma',
    'map05226': 'Gastric cancer',
    'map05214': 'Glioma',
    'map05216': 'Thyroid cancer',
    'map05221': 'Acute myeloid leukemia',
    'map05220': 'Chronic myeloid leukemia',
    'map05217': 'Basal cell carcinoma',
    'map05218': 'Melanoma',
    'map05211': 'Renal cell carcinoma',
    'map05219': 'Bladder cancer',
    'map05215': 'Prostate cancer',
    'map05213': 'Endometrial cancer',
    'map05224': 'Breast cancer',
    'map05222': 'Small cell lung cancer',
    'map05223': 'Non-small cell lung cancer',
    # === Infectious diseases – Viral ===
    'map05166': 'Human T-cell leukemia virus 1 infection',
    'map05170': 'Human immunodeficiency virus 1 infection',
    'map05161': 'Hepatitis B',
    'map05160': 'Hepatitis C',
    'map05171': 'COVID-19',
    'map05164': 'Influenza A',
    'map05162': 'Measles',
    'map05168': 'Herpes simplex virus 1 infection',
    'map05163': 'Human cytomegalovirus infection',
    'map05169': 'Epstein-Barr virus infection',
    'map05165': 'Human papillomavirus infection',
    # === Infectious diseases – Bacterial ===
    'map05110': 'Vibrio cholerae infection',
    'map05120': 'Helicobacter pylori infection',
    'map05130': 'Pathogenic Escherichia coli infection',
    'map05132': 'Salmonella infection',
    'map05131': 'Shigellosis',
    'map05135': 'Yersinia infection',
    'map05133': 'Pertussis',
    'map05134': 'Legionellosis',
    'map05150': 'Staphylococcus aureus infection',
    'map05152': 'Tuberculosis',
    'map05100': 'Bacterial invasion of epithelial cells',
    # === Infectious diseases – Parasitic ===
    'map05146': 'Amoebiasis',
    'map05144': 'Malaria',
    'map05145': 'Toxoplasmosis',
    'map05140': 'Leishmaniasis',
    'map05142': 'Chagas disease',
    'map05143': 'African trypanosomiasis',
    # === Immune diseases ===
    'map05310': 'Asthma',
    'map05322': 'Systemic lupus erythematosus',
    'map05323': 'Rheumatoid arthritis',
    'map05320': 'Autoimmune thyroid disease',
    'map05321': 'Inflammatory bowel disease',
    'map05330': 'Allograft rejection',
    'map05332': 'Graft-versus-host disease',
    'map05340': 'Primary immunodeficiency',
    # === Neurodegenerative diseases ===
    'map05010': 'Alzheimer disease',
    'map05012': 'Parkinson disease',
    'map05014': 'Amyotrophic lateral sclerosis',
    'map05016': 'Huntington disease',
    'map05017': 'Spinocerebellar ataxia',
    'map05020': 'Prion disease',
    'map05022': 'Pathways of neurodegeneration',
    # === Substance dependence ===
    'map05030': 'Cocaine addiction',
    'map05031': 'Amphetamine addiction',
    'map05032': 'Morphine addiction',
    'map05033': 'Nicotine addiction',
    'map05034': 'Alcoholism',
    # === Cardiovascular diseases ===
    'map05417': 'Lipid and atherosclerosis',
    'map05418': 'Fluid shear stress and atherosclerosis',
    'map05410': 'Hypertrophic cardiomyopathy',
    'map05412': 'Arrhythmogenic right ventricular cardiomyopathy',
    'map05414': 'Dilated cardiomyopathy',
    'map05415': 'Diabetic cardiomyopathy',
    'map05416': 'Viral myocarditis',
    # === Metabolic diseases ===
    'map04930': 'Type II diabetes mellitus',
    'map04940': 'Type I diabetes mellitus',
    'map04936': 'Alcoholic liver disease',
    'map04932': 'Non-alcoholic fatty liver disease',
    'map04931': 'Insulin resistance',
    'map04933': 'AGE-RAGE signaling pathway in diabetic complications',
    'map04934': 'Cushing syndrome',
    # === Drug resistance ===
    'map01501': 'beta-Lactam resistance',
    'map01502': 'Vancomycin resistance',
    'map01521': 'EGFR tyrosine kinase inhibitor resistance',
    'map01524': 'Platinum drug resistance',
    'map01522': 'Endocrine resistance',
}

# Build the full KEGG_NAMES dict with both 'map' and 'ko' prefixes
# 'ko' entries use the same name (no suffix) since ko and map both describe
# the same biological pathway — the prefix simply indicates the annotation source.
KEGG_NAMES: dict[str, str] = {}
for _code, _name in _MAP.items():
    KEGG_NAMES[_code] = _name                        # mapXXXXX
    KEGG_NAMES['ko' + _code[3:]] = _name             # koXXXXX  (same name)


def pathway_label(code: str) -> str:
    """Return human-readable name for a KEGG pathway code (ko or map prefix).
    Falls back to the raw code if not found in the lookup table.
    """
    return KEGG_NAMES.get(code.strip(), code.strip())
